### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [2]:
#np.array

import numpy as np 

a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
#2D 
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
# 3D
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
#dtype
print(np.array([1,2,3],dtype=float))
print(np.array([1,2,3],dtype=bool))
print(np.array([1,2,3],dtype=complex))


[1. 2. 3.]
[ True  True  True]
[1.+0.j 2.+0.j 3.+0.j]


In [6]:
#np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [7]:
#with reshape
print(np.arange(16).reshape(2,2,2,2))
np.arange(16).reshape(4,2,2)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [8]:
#np.random 
np.random.random((3,4,2))

array([[[0.84304055, 0.18019578],
        [0.8268359 , 0.03266824],
        [0.31936835, 0.13135227],
        [0.41918755, 0.62847108]],

       [[0.78197402, 0.06090244],
        [0.01108188, 0.86317605],
        [0.49981564, 0.94634932],
        [0.6630512 , 0.85356866]],

       [[0.48750037, 0.06519651],
        [0.02110305, 0.93673063],
        [0.04874528, 0.94442047],
        [0.84375631, 0.37589179]]])

In [9]:
#np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [10]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attributes

In [11]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [12]:
#ndim - tells dimension of array
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [13]:
#shape - tell about rows and columns
#In 3d first tell -how many 2D arrays
# second and third tell about row and column
print(a1.shape)
print(a2.shape)
print(a3.shape)
a3

(10,)
(3, 4)
(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [14]:
#size - no of items
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [15]:
#itemsize - tell about size of item
print(a1.itemsize) #int
print(a2.itemsize) #float
print(a3.itemsize) #float

4
8
8


In [16]:
#dtype - tell about data type
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


Changing datatype

In [17]:
#astype
print(a3)
print(a3.dtype)
b = a3.astype(np.int32)
print(a3.dtype)
print(b)
b.dtype

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
int64
int64
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


dtype('int32')

Array operation

In [21]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1)
print(a2)

a2/a2
a1*a1

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [35]:
#scalar operations

# arithmetic
print(a1)
ww =  a1* 2
print(a1)
print(ww)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [36]:
#relational
print(a2>15)
print(a2==15)


[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False  True]
 [False False False False]
 [False False False False]]


In [37]:
#VECTOR OPERATIONS
#ARITHMETIC

# a1 ** a2
# a1+ a2
#a1 *a2
a1 / a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

Array Functions

In [38]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[80., 95., 24.],
       [12., 13., 97.],
       [89., 69., 84.]])

In [39]:
#max/min/sum/prod

print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

97.0
12.0
563.0
1423769056819200.0


In [40]:
# 0 - col and 1 ->row
print(np.max(a1,axis=0))
print(np.prod(a1,axis=0))
a1

[89. 95. 97.]
[ 85440.  85215. 195552.]


array([[80., 95., 24.],
       [12., 13., 97.],
       [89., 69., 84.]])

In [55]:
#mean/median/std/var
print(np.mean(a1,axis = 1))
print(np.median(a1,axis = 1))
print(np.std(a1,axis = 1))
print(np.var(a1,axis = 1))

[60.33333333 37.66666667 89.        ]
[58. 49. 89.]
[ 4.78423336 16.02775371  2.44948974]
[ 22.88888889 256.88888889   6.        ]


In [56]:
#trignometric func
np.sin(a1)

array([[-0.521551  , -0.85551998,  0.99287265],
       [-0.95375265, -0.95375265,  0.65028784],
       [-0.92345845, -0.77946607,  0.86006941]])

In [57]:
# dot product
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [59]:
#log and exponents
np.log(a1)
np.exp(a1)

array([[2.09165950e+24, 1.25236317e+29, 1.54553894e+25],
       [1.90734657e+21, 1.90734657e+21, 3.26901737e+06],
       [2.23524660e+37, 9.01762841e+39, 4.48961282e+38]])

In [60]:
#round?floor?ceil

np.round(np.random.random((2,3))*100)

array([[30., 51., 15.],
       [84., 77., 53.]])

In [61]:
np.floor(np.random.random((2,3))*100)

array([[56., 92.,  7.],
       [44., 45., 84.]])

In [62]:
np.ceil(np.random.random((2,3))*100)

array([[96., 33., 52.],
       [40., 53., 35.]])

### Indexing and Slicing

In [63]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [64]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
a1[0]
a1[-1]

np.int64(9)

In [67]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
#print(a2[row,column])
print(a2[2,3])
print(a2[1,2])
print(a2[0,2])

11
6
2


In [72]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [73]:
#a3[no of 2d array,row , column]
a3[1,0,1]

np.int64(5)

In [76]:
a3[1,1,0]

np.int64(6)

In [77]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
a1[2:5]

array([2, 3, 4])

In [79]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0,:] #row 1

array([0, 1, 2, 3])

In [ ]:
a2[:,2] #col 3

array([ 2,  6, 10])

In [82]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [83]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [84]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [87]:
a2[1:2,::3]

array([[4, 7]])

In [88]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [93]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [94]:
a3[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [96]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [97]:
a3[0,1:2,:]

array([[3, 4, 5]])

In [98]:
a3[1,:,1]

array([10, 13, 16])

In [99]:
a3[2:,1:,1:]

array([[[22, 23],
        [25, 26]]])

In [100]:
a3[0::2,0:1,0::2]

array([[[ 0,  2]],

       [[18, 20]]])

### Iterating

In [101]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [104]:
a1 
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [105]:
a2
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [106]:
a3

for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3): # convert n -dimension array into 1 dimension
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Reshaping

In [110]:
#Transpose
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [113]:
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
#ravel - convert in 1-d array
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
print(a2.ravel()) 
a2

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Stacking

In [118]:
#horizonatal stacking

a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [120]:
np.hstack((a4,a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [121]:
#verticalstacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#Splitting

In [122]:
#horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [127]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [128]:
#vertiacl splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [129]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

HW


In [41]:
import numpy as np

In [58]:
#1

a = np.array([0]*10).reshape(5,2)
a[4] = 1
a

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1]])

In [56]:
#2
a = np.random.random(12).reshape(6,2)*100
print(a)
np.mean(a)

[[14.3009841  22.40692682]
 [91.6145725  22.5798236 ]
 [10.14092242 34.02284619]
 [69.0951909   3.34245319]
 [43.28846269 37.7756551 ]
 [17.82091543 72.29841185]]


np.float64(36.55726373181101)

In [ ]:
a = np.array([0]*16).reshape(4,4)
a

i=0

while(i<4):
    j=0
    while(j<4):
        if (i == 0 or i==3) or (j==0 or j==3)  :
            a[i][j] = 1
        j +=1
    i+=1

a


True

In [81]:
#4
a = np.random.random(10)

while 0 in a:
    a = np.random.random(10)

a


array([0.11961771, 0.67119275, 0.38387859, 0.76819904, 0.847911  ,
       0.75790836, 0.60512486, 0.6171936 , 0.78182759, 0.19476815])

In [86]:
#4

np.linspace(0,1,12)[1:11]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [ ]:
#5

#no

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [101]:
#6
a = np.array([0,1,2,3,4]*5).reshape(5,5)
print(a)
a+2

#or

z = np.zeros((5,5))
z+= np.arange(5)
z

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [112]:
#6
#np.linspac
import math
a = np.random.randint(1,100,(10,2))
point = np.array([2,3]) 

#sqrt((2-6)**2 + (3-34)**2)

np.sqrt(np.sum((a-point)**2,axis=1)).astype(int)

array([ 82,  23,  93,  82,  66,  93,  87,  86, 100, 101])

In [123]:
a = np.random.randint(1,100,(6,7,8))

b = a.ravel()

c = 100

no_2d = 100//56
no_2d

row = (100-56)//8
row

col = 44-(8*row)-1
col

l = [no_2d,row,col]
l

[1, 5, 3]

In [136]:
a = (input("enter")).split()

g = np.array(a[::-1],dtype=float)
g

array([5., 4., 3., 2., 1.])

In [139]:
#10

a = np.arange(16)
a
np.size(a)
type(a)

numpy.ndarray

In [190]:
class Err(Exception):

    def __init__(self,message):
        print(message)

def staack(*args):
    for i in args:   
        if type(i) is not np.ndarray :
            raise Err("Not a numpy array")
    return np.vstack(args)
    
        
try:
    a = np.arange(16).reshape(4,4)
    print(a)
    b = np.arange(16).reshape(4,4)
    print(staack(a,b))
except Exception as e:
    print(e)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [215]:
def date(start,end):
    l1 = start.split('-')
    l2 = end.split('-')
    end_date = int(l2[2]) 
    start_date =  int(l1[2])
    diff = end_date - start_date
    a = np.array(['2020-09-']*(diff+1))
    b = np.arange(start_date,end_date+1)
    str_date = b.astype(str)
    c = a + str_date
    print(c)


date('2020-09-16','2020-08-25')

['2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19' '2020-09-20'
 '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24' '2020-09-25']


In [224]:
#15
a = np.arange(16).reshape(4,4)
print(a)


a[:,[1,2]] = a[:,[2,1]]
a

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[ 0,  2,  1,  3],
       [ 4,  6,  5,  7],
       [ 8, 10,  9, 11],
       [12, 14, 13, 15]])