### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [3]:
#code
import numpy as np
a = np.random.randint(1,100,15)
a

array([86, 20, 86, 21, 60, 69, 36, 32, 97, 32, 48, 89, 55, 89, 52],
      dtype=int32)

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[45, 84, 93,  8],
       [57,  1, 48, 27],
       [ 3, 28, 24, 44],
       [42, 56, 34, 44],
       [73, 92,  3,  6],
       [43, 97, 17, 84]], dtype=int32)

In [9]:
print(np.sort(a))
np.sort(a)[::-1]

[20 21 32 32 36 48 52 55 60 69 86 86 89 89 97]


array([97, 89, 89, 86, 86, 69, 60, 55, 52, 48, 36, 32, 32, 21, 20],
      dtype=int32)

In [7]:
np.sort(b,axis=0)

array([[ 3,  1,  3,  6],
       [42, 28, 17,  8],
       [43, 56, 24, 27],
       [45, 84, 34, 44],
       [57, 92, 48, 44],
       [73, 97, 93, 84]], dtype=int32)

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [10]:
#code
np.append(a,200)

array([ 86,  20,  86,  21,  60,  69,  36,  32,  97,  32,  48,  89,  55,
        89,  52, 200])

In [11]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[45., 84., 93.,  8.,  1.],
       [57.,  1., 48., 27.,  1.],
       [ 3., 28., 24., 44.,  1.],
       [42., 56., 34., 44.,  1.],
       [73., 92.,  3.,  6.,  1.],
       [43., 97., 17., 84.,  1.]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [12]:
#code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [13]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [15]:
#code

e = np.array([1,1,2,2,2,2,2,3,4,5,5,6])

np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [ ]:
#code

print(a)

array([86, 20, 86, 21, 60, 69, 36, 32, 97, 32, 48, 89, 55, 89, 52],
      dtype=int32)

In [17]:
np.expand_dims(a,axis=0)

array([[86, 20, 86, 21, 60, 69, 36, 32, 97, 32, 48, 89, 55, 89, 52]],
      dtype=int32)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [18]:
a

array([86, 20, 86, 21, 60, 69, 36, 32, 97, 32, 48, 89, 55, 89, 52],
      dtype=int32)

In [19]:
#find all indices with value greater than 50
np.where(a>50)

(array([ 0,  2,  4,  5,  8, 11, 12, 13, 14]),)

In [20]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 0, 20,  0, 21,  0,  0, 36, 32,  0, 32, 48,  0,  0,  0,  0],
      dtype=int32)

In [21]:
np.where(a%2==0,0,a)

array([ 0,  0,  0, 21,  0, 69,  0,  0, 97,  0,  0, 89, 55, 89,  0],
      dtype=int32)

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [22]:
#code
a

array([86, 20, 86, 21, 60, 69, 36, 32, 97, 32, 48, 89, 55, 89, 52],
      dtype=int32)

In [23]:
np.argmax(a)

np.int64(8)

In [24]:
np.argmax(b,axis=0)

array([4, 5, 0, 5])

In [25]:
np.argmax(b,axis=1)

array([2, 0, 3, 1, 1, 1])

In [26]:
#np.argmin()

np.argmin(a)

np.int64(1)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [27]:
a

array([86, 20, 86, 21, 60, 69, 36, 32, 97, 32, 48, 89, 55, 89, 52],
      dtype=int32)

In [28]:
np.cumsum(a)

array([ 86, 106, 192, 213, 273, 342, 378, 410, 507, 539, 587, 676, 731,
       820, 872])

In [29]:
b

array([[45, 84, 93,  8],
       [57,  1, 48, 27],
       [ 3, 28, 24, 44],
       [42, 56, 34, 44],
       [73, 92,  3,  6],
       [43, 97, 17, 84]], dtype=int32)

In [ ]:
np.cumsum(b,axis=0)

array([[ 45,  84,  93,   8],
       [102,  85, 141,  35],
       [105, 113, 165,  79],
       [147, 169, 199, 123],
       [220, 261, 202, 129],
       [263, 358, 219, 213]])

In [33]:
np.cumsum(b,axis=1)

array([[ 45, 129, 222, 230],
       [ 57,  58, 106, 133],
       [  3,  31,  55,  99],
       [ 42,  98, 132, 176],
       [ 73, 165, 168, 174],
       [ 43, 140, 157, 241]])

In [34]:
np.cumprod(a)

array([                  86,                 1720,               147920,
                    3106320,            186379200,          12860164800,
               462965932800,       14814909849600,     1437046255411200,
          45985480173158400,  2207303048311603200, -6464213511072382976,
       -5043605708499582976, -6159050287433646080, -6675965693487218688])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [35]:
a

array([86, 20, 86, 21, 60, 69, 36, 32, 97, 32, 48, 89, 55, 89, 52],
      dtype=int32)

In [36]:
np.percentile(a,100)

np.float64(97.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [37]:
#code
a

array([86, 20, 86, 21, 60, 69, 36, 32, 97, 32, 48, 89, 55, 89, 52],
      dtype=int32)

In [38]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 0, 2, 3, 1, 2, 2, 0, 4, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [39]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [41]:
items = [10,20,30,40,50,60,70,80,90,100]
print(np.isin(a,items))
a[np.isin(a,items)]

[False  True False False  True False False False False False False False
 False False False]


array([20, 60], dtype=int32)

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [42]:
a

array([86, 20, 86, 21, 60, 69, 36, 32, 97, 32, 48, 89, 55, 89, 52],
      dtype=int32)

In [43]:
np.flip(a)

array([52, 89, 55, 89, 48, 32, 97, 32, 36, 69, 60, 21, 86, 20, 86],
      dtype=int32)

In [44]:
b

array([[45, 84, 93,  8],
       [57,  1, 48, 27],
       [ 3, 28, 24, 44],
       [42, 56, 34, 44],
       [73, 92,  3,  6],
       [43, 97, 17, 84]], dtype=int32)

In [ ]:
np.flip(b) # flip row then column

array([[84, 17, 97, 43],
       [ 6,  3, 92, 73],
       [44, 34, 56, 42],
       [44, 24, 28,  3],
       [27, 48,  1, 57],
       [ 8, 93, 84, 45]], dtype=int32)

In [45]:
np.flip(b,axis=1)

array([[ 8, 93, 84, 45],
       [27, 48,  1, 57],
       [44, 24, 28,  3],
       [44, 34, 56, 42],
       [ 6,  3, 92, 73],
       [84, 17, 97, 43]], dtype=int32)

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [49]:
#code
a

array([110, 530,  86,  21,  60,  69,  36,  32,  97,  32,  48,  89,  55,
        89,  52], dtype=int32)

In [ ]:
np.put(a,[0,1],[110,530]) #permanent change

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [50]:
a

array([110, 530,  86,  21,  60,  69,  36,  32,  97,  32,  48,  89,  55,
        89,  52], dtype=int32)

In [51]:
np.delete(a,0)

array([530,  86,  21,  60,  69,  36,  32,  97,  32,  48,  89,  55,  89,
        52], dtype=int32)

In [52]:
np.delete(a,[0,2,4])

array([530,  21,  69,  36,  32,  97,  32,  48,  89,  55,  89,  52],
      dtype=int32)

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [53]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [54]:
np.intersect1d(m,n)

array([3, 4, 5])

In [55]:
np.setdiff1d(m,n)

array([1, 2])

In [56]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [58]:
m[np.in1d(m,1)]

C:\Users\HP\AppData\Local\Temp\ipykernel_18756\524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [59]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 25, 60, 69, 36, 32, 75, 32, 48, 75, 55, 75, 52],
      dtype=int32)